### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by smusali**

### CODE REVIEW

**Comment by vilyapilya** [comment]
Furthermore, the release related change should not make code changes unless it is necessary

**Comment by smusali** [comment]
> Furthermore, the release related change should not make code changes unless it is necessary

There is no code change here but structure change

**Comment by smusali** [comment]
> I don't agree with puting tests.rb file into a tests. folder.

Why? Keeping all tests in the same folder is as good as keeping all source code libraries in `lib` folder. It’s always better to keep them in one place for the sake of proper and clean structure.

**Comment by vilyapilya** [comment]
There is only one file, it is silly to put a single file into a folder.

**Comment by smusali** [comment]
> There is only one file, it is silly to put a single file into a folder.

I have placed them back

**Pull request merged**
